### ISSUE TITLE
Project Defense

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#37]
@FiXerCz , @dvori , @kiclus ,
the project defense dates are available now, so please let me know (**all of you**) *here* which ones do you prefer **sorted** by your preference.

These are the available dates:
> Mon 19.1. 17:30-22:00 (B130)
> Tue 27.1. 16:30-20:00 (B130)
> Wed 28.1. 15:00-20:00 (B130)
> Thu 29.1. 15:00-16:00 (B130)
> Thu 29.1. 19:00-20:00 (B130)

My preference:
Thu 29.1. 15:00-16:00 (B130)
Thu 29.1. 19:00-20:00 (B130)
Wed 28.1. 15:00-20:00 (B130)
Mon 19.1. 17:30-22:00 (B130) (if need be, I have an exam before)
Tue 27.1. 16:30-20:00 (B130) (I'd rather avoid it, I have an exam from this course 2.5 hours before and it would be too much Java for one day :smiley: )

But, even if we picked 19. 1., there would still be plenty of time to finish the project.

**Comment by dvori** [comment]
I have exam from Java at Mon 19.1, so Monday should be best for me, but rest of dates are also OK for me.

**Comment by FiXerCz** [comment]
*Mon 19.1. 17:30-22:00 (B130)*
*Wed 28.1. 15:00-20:00*
*Tue 27.1. 16:30-20:00 (B130)* - I also have Java exam here, but as I have metric f*ckton of exams this semester, I cannot be very picky
Thu 29.1. 19:00-20:00 (B130) - in case I f*ck up Automatons tomorow, there is another exam date here
Thu 29.1. 15:00-16:00 (B130) - in case I f*ck up Automatons tomorow, there is another exam date here

Since tomorow evening i should have couple of days to look into our project so if any more of you have time, we can finish it.. and bury it... deep....

**Comment by Cweorth** [comment]
Ad Automatons: I'm sure you will be fine. Look at the yesteryear's tests, they are not that bad.
Ad burying something somewhere... You are right, those "TravelAgency" related project we have seen before on Google Code are much stinkier I think :smiley:

**Comment by FiXerCz** [comment]
Yeah, I did not mean that our project is bad :) On the contrary I think we are in a higher-quality-projects group from this subject, but it's already dragging very long time and I will be happier when the pressure of finalizing/presenting/keeping deadlines will be over :)

**Comment by Cweorth** [comment]
*Thu 29.1. 15:00-16:00 (B130)* is full now. @kiclus please, respond ASAP

**Comment by dvori** [comment]
If he doesn't answer till noon, You should choose dates according to our three answers

**Comment by Cweorth** [comment]
Well, I don't suppose I can do that; if I chose the date that wouldn't suit him and he wouldn't come to the defense, both we and him would have a problem. I **could** choose a date and later change it when required **if** they used the *exam scheduling application*, but the way it is now I'm not sure the date can be changed later.

**Comment by FiXerCz** [comment]
Do you either have a FB contact on him? If so, try leaving him a message there. Maybe he switched off notifications from GitHub.

**Comment by Cweorth** [comment]
The checked the last email I sent, he is in "To" so it should have reached him. But yes, I shall leave him a notification on the NSA-DB

**Comment by FiXerCz** [comment]
:)

**Comment by kiclus** [comment]
I must heva all clear to 4.2 everything befere that is posible, I have only one exams and it is java 19. and secound defend from another course but it is not in this times.

**Comment by kiclus** [comment]
sory guis I was totaly destroy for 3 days I Must reorganise part of mi graduation teases. I vant end this course soon as posible but I dont knou how hard is the last reques

**Comment by Cweorth** [comment]
According to our preferences, the one that's not full AND is as soon as possible WITH **no** objections against is *Wed 28.1. 15:00-20:00 (B130)*. Also, it will give us another 9 days to finish the project, so I choose this one.
*Mon 19.1. 17:30-22:00 (B130)* would probably be fine too, but then the project would have to be completed on 16.1., presentation on 18.1. and I fear that 8 days to finish the project might not be enough.
