### ISSUE TITLE
Password hashing

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#38]
I have noticed in your last commit 6e0c7c48fe60adba525dff0be3b3f9abc6f66706 that you mention password hashing. Doesn't Spring already do that? If not, can we use some kind of hashing with salt?

Btw, good work with the Account DAO/Service.

**Comment by FiXerCz** [comment]
> I have noticed in your last commit 6e0c7c4 that you mention password hashing. Doesn't Spring already do that?

That is highly probable. I did not do some thorough research if it does yet :)

Give me max 5 minutes and I will push changes that add roles to our Account entity. That should be all basic stuff needed to start setting up spring security.

**Comment by Cweorth** [comment]
Fair enough. I'm still at work, so I can't officially do this, but let me know what you will work on, so I could do something different (to make sure our changes won't clash). I also think I know what the others can do ... you will like it :smiley:

**Comment by FiXerCz** [comment]
Alright it was 10 minutes. I overestimated myself :)

**Comment by FiXerCz** [comment]
So spring sec. does nothing automatic to hash + salt passwords, but it can be achieved by registering *bcrypt* to spring sec.

I will have to modify Account DAO code to hash + salt password with bcrypt too.

**Comment by Cweorth** [comment]
Now that I start to think about it, our user roles system that we were counting on from the start is a little bit flawed :smiley: You see, in order to create excursions and trips the user need to be the administrator, but therefore he can access everything (customers etc.).

So, is there some easy way to add a new role (like ```ROLE_STAFF```) that will be able to add new trips and excursions, but will not have administrator rights? The ordering of privileges would be like ```ROLE_USER``` < ```ROLE_STAFF``` < ```ROLE_ADMIN```.

If that would be too much work, then forget it, it's just an enhancement thought.

**Comment by FiXerCz** [comment]
Sure, it is just about adding one new entry to enum. No problema. In the app, we will then just check what roles user has (user, admin, staff) or if he is just unauthenticated loser :)

I am trying to add spring sec., but I made stupid design of the two role-related tables (they are joined based on ID, not username), so I must deal with it somehow. When configuring spring sec, one must make available 2 queries for selecting username+password and username+role looked up by username. Some join query should work hopefully..

**Comment by Cweorth** [comment]
It seems to me that -- by assignment -- an user must always be logged on in order to access the services (reservations, trips, excursions). So, unauthenticated looser would see the login screen at best :smiley:

Try adding eager fetch to the entity. We will have at most 3 roles, so that would not slow it down very much and you might save yourself the extra query.

**Comment by FiXerCz** [comment]
Shouldn't it be possible for unauthenticated user to view excursions and trips? There should not be any harm in that. But it would maybe mean a bit more work. And that would suck :)

**Comment by Cweorth** [comment]
Well ... we can add exclusive role ```ROLE_GUEST``` that would be implicit when until you log on and after you log out, and make sure by DAO layer that there is only one guest in the DB and it has no other roles ... that's possible, not very much work ...

**Comment by Cweorth** [comment]
Or we could simply treat ```null``` account as guest, but we should never rely on ```null``` values :smiley:

**Comment by FiXerCz** [comment]
I need to go out to deal with some stuff, so I will make a commit with what I have + info about it. I will have some time for it a bit later.

If you will want to make changes to the code or try to pick up where I left off, just leave me a message here on Github :)

**Comment by Cweorth** [comment]
I will get off the work in an hour, so maybe when I arrive "home".

**Comment by FiXerCz** [comment]
So I am back at PC for a little while. My previous commit has a small error in one of the authentication queries. I have already fixed it and managed to get the authentication process working. I will make a commit that fixes that mistake and adds some basic login templates. Hopefully I will make it tonight.

**Comment by Cweorth** [comment]
Sorry it took me so long, unexpected complications after workd :smiley: I'm just looking at your work, and in ```Account.java``` on line 39 in the definition of ```roles```, you should rename the table in annotation ```@CollectionTable``` to get rid of the SQL warning (```ROLE``` is apparently a reserved word in SQL).
Apart from that, you did a very good job. I'm not sure what should I do to no cause a conflict. What are you working on right now?

**Comment by FiXerCz** [comment]
No problem.

I will try to make that promised commit before 22:30 (but you know my loose time limits :D ). I think that nothing terrible will happen if you put your feet up for today and code tomorow. Or you can wait till I commit my code and go on today :)

When I commit I will again write stuff that are done and those that are needed to be done and we can switch - you will code for a while and we can switch again etc etc :)

> I'm just looking at your work, and in Account.java on line 39 in the definition of roles, you should rename the table in annotation @CollectionTable to get rid of the SQL warning (ROLE is apparently a reserved word in SQL).

I think I can rename it to "authority". I have seen it to be called as such :)

**Comment by FiXerCz** [comment]
The promised commit is finally pushed -  237ef3a811753b8750439e146c43985ea6ae958d. It is now possible to log in/out.

**What is already done:**

1) Spring-sec config file is more or less finished and working.
2) There is basic login form that is shown at page /login and could be possibly inserted to main page too.
3) Top right corner has Sign in/up links for non-authenticated and Sign out for authenticated.
4) There is a global super-awesome-all-powerfull user with all privileges with username *pa165* and password *pa165*. It may not look it but I have given a lot of thought in these credentials :smiley: This user is TEMPORARILY created in PostInit method of ```CustomerController.java```. It is there just for convenience during coding and should be moved someplace else.

**What should be done:**

1) Sign up page is non-existent and also it will need some simple *AccountController*, so that users can register themselves. This controller should perhaps also do checking if user can create his/her Customer object and mediate its creation.
2) Accounts created by registering should have only *ROLE_USER*.
3) Views and controller methods should be accessible only for users with appropriate roles. So we will have to annotate some methods and add <sec:...> tags to some views.

If I have forgotten anything, just post a message :smile: I know it took me a while, but I think it was worth the wait. We are much closer to the finish line.

Let me know when you check code (there may be some errors) and decide, what you will work on.

GN!

**Comment by Cweorth** [comment]
You did a great amount of work today, sir. You don't need to hurry now, I thought it would take quite longer :smiley: (and I also thought I would have more time & that my Linux would work ... which it does not, and I refuse to code while on Windows)

Creating users in ```PostInit``` is necessary, how else could you create the "first" one? But I think we should unify all ```PostInit```s into one and create more ... "*presentable*" examples if you know what I mean :smiley: This is **Surreal**-Travel, our destinations should reflect that...

Also, I think we should incorporate some code that will make sure there is always some user with administrative privileges. This should be explicit, like the user ```root``` (or ```admin```) that is not able to renounce his privileges. ```pa165``` is required by the requirements, but it does not state that it should have all the priviliges (right?). But that's not important right now, this can be changed later.

Ad specific tasks:
1) You mean that ```Account``` and ```Customer``` will be created at once by the form, right? I will look at it tomorrow.
2) Exactly. I would be quite scared of a real-world IS would allow a complete stranger to assume administrator rights :smiley: but this implies the previous thought, that there always should be at least one administrator that could always access the whole system
3) Yes, that's specified in the requirements.

Again, very good work you have done there.

**Comment by Cweorth** [comment]
I will also create ```list``` and other methods for ```AccountController``` and will map ```/register``` to ```/accounts/add```, which will be the only method of this controller available to public. I think I will also enable ```/accounts/{id}``` to be available to the currently logged user, but only for his ID. Others will require administrator rights.
