### ISSUE TITLE
Account DAO Unit Tests

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#39]
Your task should be very clear from the title I hope.

**Comment by kiclus** [comment]
I have some problem with the exception No transactional entity manager awayble. I call the AccountDao by @Autowired. I can find if in the beans are mistake or I must these tests do some other way. I find that in other tests Dao are calling same way by Autowired, but there are no exception. I cant find where must be the accountDao defined or where is defined wrong.

**Comment by Cweorth** [comment]
There is ```@Transactional``` annotations missing for your test class.

Also, two notes regarding the class:
   - remove the empty parameter-less constructor,
   - in ```testAddAccount``` you should not assume that all IDs are greater than 0; this may depend on the database configuration.

**Comment by kiclus** [comment]
Thanks, I hate this stupid mistake I was watching hole code where is the mistake.

**Comment by kiclus** [comment]
I have in my teests addAccountNullCustomer() test and the pass, with null customer in adding account. maybe is better to make in JPA nullpointerException . because make Account without customer is nonsence. But we can leaw it lik it is.

**Comment by FiXerCz** [comment]
It makes sense. Customer is not required for roles staff and admin and even cannot be assigned to root. Customer is used for creating reservations and staff and admins are not very likely to create reservations for themselves.

**Comment by Cweorth** [comment]
@FiXerCz is 99% right, we allow accounts with no ```Customer``` assigned.

(The only difference is that there is no reason why ```root``` shouldn't have it, we can attach it in code, but there is no way to do so in the application... but we can pretend we don't know about that :speak_no_evil:  )
