### ISSUE TITLE
Account Service Unit Tests

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#40]
Your task is fully specified in the title.

**Comment by dvori** [comment]
Almost done, just need to fix update and delete test ...

**Comment by kiclus** [comment]
HI guys. Im sorry to dont respond I have got Today defence of other project as I write in the E-mail (because they change milestones for mi in other subject).Now I am full awayble to hepl you.

**Comment by FiXerCz** [comment]
> HI guys. Im sorry to dont respond I have got Today defence of other project as I write in the E-mail (because they change milestones for mi in other subject).Now I am full awayble to hepl you.

There is another issue assigned to you (Account DAO test). Please do that.

**Comment by dvori** [comment]
@FiXerCz  can you please look on your update and delete method in "DefaultAccountService" ... 
In delete method I'm stuck on testing (account == null)
In update method don't know where is the problem ...

**Comment by Cweorth** [comment]
I'm the one who made security changes in these methods.

**Ad delete**: it seems that you will not be able to reasonably fix the problem with ```removeAccountById```. It requires valid ```SecurityContextHolder``` to verify that you really can delete the account. So you can skip this test.

**Ad update**: it should be possible, but thanks to the fact that the test fails I found out that on service layer there is a security hole, where an user can edit administrator's account. (That's probably not cool). So, you can skip this test as well, as it will again require ```SecurityContextHolder```.

I'm not saying it's impossible, but it's quite complex. If there is some time left, I will look into that.
Sorry for this, I should have seen this problem sooner.

**Comment by dvori** [comment]
OK, I deleted these two metods form the test file and commit new version.

**Comment by FiXerCz** [comment]
Sorry to reopen this, but I managed to "fix" the update method (did not have time to look at the delete yet).

When writing the test, one just needs to keep in mind that anything that is done by DAO, must be specified in the test, as the object is mock.

So adding 3 "when" method calls solves the issue:
```java
AccountDTO tripToUpdate = accounts.get(0);
Account entity = mapper.map(tripToUpdate, Account.class);
when(dao.updateAccount(entity)).thenReturn(entity);
when(dao.getAccountByUsername("root")).thenReturn(null);
when(dao.getAccountById(entity.getId())).thenReturn(entity);
service.updateAccount(tripToUpdate);
verify(dao, times(1)).updateAccount(entity);
```

Also, for some weird reason the ```checkRoles()``` method call in ```updateAccount()``` is ignored in test, so when creating test accounts in test constructor, it is neccessary to specify all roles, not just the highest one.

```java
a1.setRoles(EnumSet.of(UserRole.ROLE_ADMIN, UserRole.ROLE_STAFF, UserRole.ROLE_USER));
```

**Comment by Cweorth** [comment]
I know. And you can close it again :smiley: ```updateAccount``` now uses ```SecurityContextHolder``` (which was missing and enabled mere user to delete admin's account). 

> One does not simply mock ```SecurityContextHolder``` 

... though I found some -- rather long -- tutorials out there. So I think this should be best left *unfixed*.

**Comment by Cweorth** [comment]
Btw, 

> Also, for some weird reason the checkRoles() method call in updateAccount() is ignored in test

it is not ignored, but Mockito will complain that you called ```verify``` with the original entity as an argument, but service method *will* add missing roles, so these would not match (hence an exception).

**Comment by FiXerCz** [comment]
Ok. Mocking of the securitycontext sounds like dark stuff and I fight for the forces of good, so I withdraw from this. Lets go with the original idea and forget about testing it :D
