### ISSUE TITLE
Arcane exception thrown when updating AccountDTO

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#43]
When calling ```accountService.updateAccount(account)``` in ```AccountController.java:179```, an exception is thrown claiming that ```account.plainPassword``` is not set:
```java
javax.validation.ConstraintViolationException: Validation failed for classes [cz.muni.pa165.surrealtravel.entity.Account] during update time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='may not be null', propertyPath=plainPassword, rootBeanClass=class cz.muni.pa165.surrealtravel.entity.Account, messageTemplate='{javax.validation.constraints.NotNull.message}'}
]
```
but I added logging into ```JPAAccountDAO``` and turns out that ```plainPassword``` **is** set correctly when calling ```accountDao.updateAccount```.

**Reproduce**:
Open WebApp > *Accounts*, edit ```pa165```, enter old and new passwords, press submit and enjoy the output.

**What I think**:
I really have no idea why this happens, but I have a hunch that it *might* be caused by the ```@Transient``` annotation.

**Comment by FiXerCz** [comment]
Sorry, my mistake. After some google searching it would appear, that Transient and NotNull should not be mixed together.

It also does not make sense, since plainPassword is supposed to be checked only when creating a new account or changing password on already persisted account. Removing NotNull from Account entity seems to solve the issue. Again, sorry, my mistake.

---

BTW, there was a missing i18n entry for password length. That was throwing an exception for me. Maybe you have it locally and excluded it from commit?

Also other detail. When we add role Admin to some account, I think we should also add Staff and User. When adding Staff, we should add User. Therefore when we check "hasRole(USER)", it is also fullfilled for Staff and Admin. Which (at least in the tutorial) is the right behaviour.

**Comment by Cweorth** [comment]
I agree. That's what I meant in my 3rd comment in #38 (ordering ```USER``` < ```STAFF``` < ```ADMIN```).
I suppose you should implement it in the ```AccountService``` transparently in the following fashion:
when creating *or* updating the account, you can perform this simple check:
```java
    Set<UserRole> roles = account.getRoles();
    if (roles.contains(UserRole.ROLE_ADMIN)) roles.add(UserRole.ROLE_STAFF);
    if (roles.contains(UserRole.ROLE_STAFF)) roles.add(UserRole.ROLE_USER);
```
so when you only add ```ADMIN``` role to an account, it will automatically grant that user the ```STAFF``` rights. Consequently, if some admin removes ```STAFF``` role of another admin, to avoid inconsistency, the right will be granted back (and we shan't consider this a bug, since administrator is supposed to be an intelligent being :smiley:₎

**Comment by Cweorth** [comment]
Ad missing i18n entry, I fear that I forgot to test this functionality. I will fix it in a moment.

**Comment by Cweorth** [comment]
Btw, there is (currently) no way to check whether an username is already used except this "inefficient" (bear in mind this is Java :smiley: ) way by 
```java
for (AccountDTO account : accounService.getAllAccounts()) {
    if (account.getUserName().equals(...) {
        /* ... */
    }
}
```
Could you plase add a method like ```getAccountByUsername()``` ?

**Comment by FiXerCz** [comment]
Sure,I'll add mentioned functionality to dao and service classes. Will take a second.

**Comment by Cweorth** [comment]
I will not write a new bug, so I post the problem with ```AccountDAO.getAccountByUsername```:
Apparently, when calling ```getSingleResult()``` and there is nothing to return, ```JPA``` throws ```javax.persistence.NoResultException``` (the API is apparently friendly as fuck :smiley:).

Please, wrap the call in ```try-catch``` block so that when ```NoResultException``` is thrown, ```null``` is returned instead.
(Another solution would be to call ```getResultList()``` and test it with ```.isEmpty()```, but that's exactly what we are trying to avoid).

**Comment by FiXerCz** [comment]
Omg, that is really unbelievable stupid. I just checked that it fetches results correctly and assumed that it returns null when not found.. I will fix it...

**Comment by Cweorth** [comment]
![Java](http://memecrunch.com/meme/HW7R/java-alien-guy/image.jpg)
