### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#44]
I have added some stuff to ```base.js``` on line ```51``` and then a function from ```151``` till the end. Since I don't understand the rest of the code (I'm not a very good JS programmer :smiley:), would you please check that?

**Comment by FiXerCz** [comment]
The code was not working in Firefox. I have rewritten it and it seems to work. But before I push anything, I need to check sth:

1) Should in account/formEdit.jsp really be state="off" for checkbox? Shouldn't it be disabled="true"? State off does not seem to be doing anything.

2) Whenever I want to edit Account with some Customer already attached, I am getting prohibited field changed exception. Did I mess sth up or was it already there? :)

3) I have changes in base.js, account/form.jsp (only removed onclick attribute) and account/formEdit.jsp (state=off to disabled=true). Can I push it (i ask just to prevent conlicts)?

**Comment by Cweorth** [comment]
1) I forgot about that. I'm not sure what attribute should it be, but definitely **NOT** ```disabled```. When you use it, the object passed back to servlet will contain a default value (ie. ```false``` or ```null```) instead of the original value for some reason only God knows.
2) This is very likely caused by the previous (probably default ```false``` is passed instead of original ```true```), that's why there is the check.
3) No, remove the ```disabled=true``` attribute, as it messes everything up.

Ad edit: I generally try to avoid changes in your code (I forgot to remove ```Transanctional(readonly = true)``` in previous commit, but you can leave it, it will help optimize queries)

**Comment by FiXerCz** [comment]
I see, in that case your JS code was maybe not faulty. To be honest I don't what is was supposed to do when editting, since whenever i click the checkbox, customer name and address remain always read-only. Was this the intention or is a mistake?

Cause my "fix" enables making name and address edittable when clicking checkbox. So I don't whether to push it or not.

**Comment by Cweorth** [comment]
It worked for me in Chrome, perhaps Firefox interprets it differently? Push it, I will cope with it later

**Comment by FiXerCz** [comment]
Changes in base.js pushed. There is note in commit message thatv account/form.jsp should have the *onChange="toggleCustomer()"* removed.

**Comment by Cweorth** [comment]
Btw:
> whenever i click the checkbox, customer name and address remain always read-only. Was this the intention or is a mistake?

It was the intention as well as temporary solution :smiley: ```USER``` and ```STAFF``` will be only able to change the password here, but administrator will be able to attach a customer to an account or change user rights here (this is yet to be implemented and the form will probably change).

Do we want to allow detaching a customer from an account as well? I don't think this functionality would make sense, but maybe it's only my opinion.

**Comment by FiXerCz** [comment]
I also think detaching customer should not be possible. Maybe, that you can change formEdit.jsp a bit - if customer is already attached, there is no need to display checkbox. You can place hidden input instead, that specifies that customer is attached to the model (hidden input with  path="customer" and value="1"). That would solve I think.
