### ISSUE TITLE
Server deployment

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#45]
I have tried to deploy the app on a "real server" (my work PC with apache installed :smiley:) and it seems it works from within the FI MU network.

Can you test whether the following works for you? ( @FiXerCz , @kiclus , @dvori  ).
It might be useful to have a backup plan in case the app won't work during presentation (well, it's Java :smiley: ).

The link is http://mens.fi.muni.cz:8080/pa165

**Comment by Cweorth** [comment]
btw, running CLI application as
```bash
$ run --url="http://mens.fi.muni.cz:8080/pa165/rest/" trips-list
```
works as well, which is nice :smiling_imp: 
(Though when you omit the last ```/``` then it fails, which should be fixed later, just a reminder for myself)

**Comment by FiXerCz** [comment]
Haha, sweet, it works for me :)

**Comment by Cweorth** [comment]
The remote app now runs on Tomcat and PostgreSQL! (so I don't need to run JavaDB from NetBeans). Though, for some reason, it's an old version...
