### ISSUE TITLE
PlainPassword in equals and hashCode makes things difficult

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#46]
Please remove ```plainPassword``` from ```equals``` and ```hashCode``` methods from both ```Account``` and ```AccountDTO``` (you may leave it in ```toString``` though).

**Reasons**: 
 - ```equals``` on ```account_a``` returned to servlet and ```account_b``` from database will always return ```false``` when form changed ```account_a.plainPassword``` (because of authentication)
 - since it is ```@Transient```, ```Account```s should *not* depend on ```plainPassword```,
 - setting ```plainPassword``` to ```null``` before every ```equals``` is tiresome and may stil bel faulty in some cases

**Comment by FiXerCz** [comment]
Alright, will do. Is it ok if I do it tomorow morning? I am not not at pc right now. If you will code yet today and this would slow you down, could you make that change in your local copy and revert local modifications tomorow as I push it?

Sorry for inconvenience.

**Comment by Cweorth** [comment]
You can do it tomorrow. I'm actually finishing my today's work, so I won't need this fix ASAP.

**Comment by FiXerCz** [comment]
Done.
