### ISSUE TITLE
Remove account in one transaction

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#48]
When removing an account, there are many operations required from service layer. Should one of these fail, the removal will fail too, but it may leave the database inconsistent.

So, I think I will move these operations to ```AccountService.removeAccount()```, so it would be covered in one transaction.

Hence my question: Do you have some changes made to ```AccountService``` locally? If so, commit and push them, please, to avoid conflicts.

---
*Btw*, if you have other changes that you don't want to push, then commit the ```AccountService``` only.

**Comment by FiXerCz** [comment]
Yo, no, I did not modify account service. On service layer I have changes only in reservation service. You can go ahead and push it.

**Comment by Cweorth** [comment]
Ok, thank you. But I will push it after I fix other errors
