### ISSUE TITLE
Security Proposal

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#49]
This issue should serve as discussion about security proposal, that our application should implement. This will also be included in ```README.md``` file, so it should be revised as "*standard-like*" :smiley:
@kiclus, @dvori, @FiXerCz  you are all welcome to express your ideas, opinions or notes if I missed something.

version 1.01

### 1. About rights
  1. rights that are not permitted are denied,
  2. rights in points ```3``` to ```6``` are **permitted** unless specified otherwise,

### 2. Privileges hierarchy:
  1.  ```ADMIN``` inherits ```STAFF``` rights,
  2. ```STAFF``` inherits ```USER``` rights,
  3. Guest (unauthenticated user) rights are **not** inherited,
  4. rights specified in the higher role have higher priority than inherited rights,

### 3. Guest rights (no authentication):
  1. list excursions and trips,
  2. login,
  3. create an account (and optionally an attached customer) with ```USER``` permissions,

### 4. ```USER``` rights
  1. logout (obviously),
  2. list excursions and trips,
  3. edit **own** account
    1. change password,
  4. remove **own** account,
  5. if contains ```Customer```
    1. edit **attached** customer,
    2. create reservation,
    3. list and remove **own** reservations,

### 5. ```STAFF``` rights
  1. create and edit excursions
     1. remove if **not referenced** by any trip,
  2. create and edit trips
      1. remove if **not referenced** by any reservation,
  3. list, edit and delete reservations,

### 6. ```ADMIN``` rights
  1. list customers and accounts,
  2. edit customers,
  3. remove customers if **not referenced** by any account or reservation,
  3. edit accounts
      1. attach customer if not present,
      2. change user rights except for the "root" account (even if logged as "root"),
  4. remove accounts
      1. all **others** except "root" account,
      2. **deny** ```4.4``` (remove own account) to "root",
  5. create, edit and remove customers **not referenced** by any account,

### 7. Default accounts

| no. | username | rights | default password | customer | 
|-----|----------------|---------|-------------------------|-----------|
| 1    | root           | ```ADMIN``` | ```root```          | *none* |
| 2    | pa165       | ```ADMIN``` | ```pa165```      | ```pa165``` |
| 3    | rest           | ```STAFF``` | ```rest```          | *none* |

-----

#### My comments:

How should we call the *root* user? ```root```, ```admin```, ```administrator```, ```pocahontas```... ?

Ad ```4.5.3``` vs ```6.5```, this means that ```USER``` (and hence ```STAFF```) cannot edit his reservation but ```ADMIN``` can, is this OK?

Ad ```6.3.1```, I'm not really sure about this, what do you think?

Ad ```6.3```, and ```6.4``` (exceptions for "root" account), this is *imho* required to make sure there is always one administrator, so the system does not turn into an anarchy,

Ad ```7```, there will of course be other accounts by default, but these should be explicitly specified in the documentation

**Comment by FiXerCz** [comment]
"Root" seems fine to me.

Ad ```4.5.3``` vs ```6.5```: Staff is currently able to see (and edit) all reservations. If staff has a Customer, then theoretically he can have Reservations and is able to edit them. Admin should definetely be able to edit all reservations.

Ad ```6.3.1``` - (should it be ```6.4.1```?) - attaching Customer would have to probably be in editting Accounts, right? Something like "if edited Account has no Customer, display select with all possible Customers"? It seems to me like a complication and it would not be trivial to achieve. I would leave it out ergo "if you want Customer, create one when creating Account or you're screwed!!" :)

Ad ```6.3```, and ```6.4``` - yeah, you are right, it should not be possible to remove root or demote it.

```Ad 7``` - Maybe user REST should be ADMIN? To ensure everything is achieveble by REST? Otherwise it seems ok, should I specify all these Accounts to be created in import.sql (by hibernate before our InitDataController)?

**Comment by Cweorth** [comment]
- ```4.5.3``` vs ```6.5``` I will fix this in the proposal.
- ```6.4.1``` (I changed numbering, sorry :smiley:) ok, I'll remove that
- ```7``` what does REST need more than access excursions and trips? As ```STAFF```, it would have all access that CLI application requires, or am I mistaken?
(All system administrators would agree: **never** give users more power than they need :smiley:)

And while I have no *strong* objections against creating these accounts in ```insert.sql```, I'd prefer the "cleaner" way as to do as less as possible in SQL (that is, create only "root" because it can't be done other way) and the rest shall be created in the initialization section in the context of the "root". Also because you need to provide hashed password, and that's not very cool. But this does not matter in the end.

Also, there is a small complication: we are required to provide password "rest", but it is only 4 characters long -- we can't break the assignment, so please make the size in the annotation from 4 instead.

**Comment by Cweorth** [comment]
BTW, can (or should) ```STAFF``` delete reservations?

**Comment by FiXerCz** [comment]
Yeah staff currently can remove reservations. I dont see it as a problem. Some "offline" can call our corporate office and ask one of our many employes to cancel his reservation. It would be weird if only system admin could do it.

**Comment by Cweorth** [comment]
All right then. If there are no more comments, I think we can implement it.
