### ISSUE TITLE
Authentication and authorization

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#50]
Implement security in both web and service layer according to #49 Security Proposal.
Since @kiclus and @dvori do not seem to be responding, we shall split it this way:
@FiXerCz : Customer, Excursion and Reservation,
@Cweorth : Trip and Account.

**Comment by FiXerCz** [comment]
We can continue discussion here as I had written it into wrong issue. :)

I will make a commit in a sec and you can see what is done and what is not..

**Comment by FiXerCz** [comment]
Ok, I have pushed it. Customer and Excursion should be finished, Reservation still has some kinks.

Also AuthCommons has a new method to redirect to denied page (and optionally show "boo-hoo" message) when some user tries to do sth, he shouldn't (when ROLE_USER edits his Customer entry and changes ID in url to different Customer for instance).

**Comment by Cweorth** [comment]
Can we add some picture there, like Gandalf's "You shall not pass?" or something similar, Gandalf is overused these days... :smiley:

**Comment by FiXerCz** [comment]
Well we can add pretty much anything to template for page /403 :)

If you want you can add it there. There is already directory for pictures in WEB-INF. Maybe some disclaimer will have to be put below it though :D

**Comment by Cweorth** [comment]
Fair enough :smiley: when there is enough time left, I will think of something

**Comment by Cweorth** [comment]
You were right, security for account is a disaster :smiley:

**Comment by Cweorth** [comment]
Mmm, I think that security requirements for edit/delete account are quite complicated, so I think I could simplify them a little bit:

| Logged in | ```self```       | ```USER```, ```STAFF``` | ```ADMIN``` | ```root```     |
|---------------|------------|---------------|----------|-----------|
| ```USER```, ```STAFF``` | ```PD```    |  **403**   | **403** | **403** |
| ```ADMIN``` | ```P*D``` | ```C*D```    | ```C*D``` | **403** |
| ```root```      |  ```P```   | ```C*D```    | ```C*D``` | ```P``` |

"Logged in" row specifies currently logged user, columns specify target of the edit/remove operation, the left-most match.

 * ```P``` - change password, require original, 
 * ```C``` - change password, original not required, 
 * ```*``` - change permissions (password required only if preceded by ```P```),
 * ```D``` - delete

That is, only root can modify his own account, which would remove some rather queer lines my code. The only drawback is that ```pa165``` will not be able to modify ```root``` (at the presentation we can pretend we don't know about it :smiley:). What do you think?

**Comment by FiXerCz** [comment]
I think that would work. It is not required of us that pa165 user should be almighty (or at least I dont see it in requirements). We can even say it at the presentation. This structure seems logical and they cannot (should not) penalize us for giving some thought about user roles. Maybe they could say that our "root" should be separate role that only one user should have but screw that.

I have some changes fixing some weird possible situations for reservations, but I will push them probably tomorow.

**Comment by FiXerCz** [comment]
Oh I did not notice that edit. I am conversing from a phone and it shows :-)

**Comment by Cweorth** [comment]
Well, the problem is the relationship between administrators. If you are an admin, you need to provide a password when changing your own password, but not if you are changing other administrator's password. This is a security nonsense.

Therefore, I will do it this way (edited the table): that is, when changing other ```ADMIN```'s password or permissions, you need to provide **your own** password so that you know what you are doing and to cover the security hole.

**Comment by FiXerCz** [comment]
Alrighty.  

Btw how do u check, that you are dealing with root? From username? Because now that I think about it adding role for root would be actually quite easy. Just addimg data to two enuma in dao and api. And checking if you are working with root would be as simple as AuthCommons.hasRole(ROLE_ROOT).

**Comment by Cweorth** [comment]
Mmm, all right, I will add it, but then we would need an extra condition to make sure no one adds another root ... that would not end well :smiley:

**Comment by FiXerCz** [comment]
If it will cause more harm than good, then we can let it go. I thought it would make it easier but did not realize the drawbacks.

**Comment by Cweorth** [comment]
**BTW**, why do we need two ```cz.muni.pa165.surrealtravel.(entity|dto).UserRole``` ? Is there a chance that we would need to map user roles? Or it is a Spring requirement? If it were my call, I'd only leave the API's ```UserRole```...

**Comment by FiXerCz** [comment]
Yeah I did it because dao does not reference the api. If you add api to dao's pom then the UserRole in DAO can be deleted. I think.

**Comment by Cweorth** [comment]
I see, there is no harm to reference API from DAO since it does not contain any actual logic ... or am I mistaken?

**Comment by FiXerCz** [comment]
No harm at all. I just did it a bit carelessly when I wrote it. I created dao first and then when dealing with service, I created new enum and let dozer do the rest instead of shifting original enum to api.

**Comment by Cweorth** [comment]
I'm just testing security in Accounts and I have noticed that ```USER``` can still see Customers link in index. Please fix it, but only after I push my changes  (I may have changed something :D)
Also, did you take into account that ```USER```/```STAFF``` that does **not** have ```Customer``` attached should not see Reservations.

**Comment by FiXerCz** [comment]
Yeah, I forgot to hide the links in this case (there is nothing shown in Customer or Reservation lists for those users but they can still see the link). I will take care of it.

**Comment by FiXerCz** [comment]
> Also, did you take into account that USER/STAFF that does not have Customer attached should not see Reservations.

I will hide it for USER, but STAFF can see it, no? Since staff can see all Reservations (not just attached to his Customer - therefore the listing is not dependent on his Customer). When adding new Reservation, STAFF sees select box with all possible Customers (unlike USER that must have Customer attached).

**Comment by FiXerCz** [comment]
Holy crap, I though I have solved hiding of Customers link in menu for staff without Customer object, but for some reason it pops back in when staff user is at "add" or "edit" page of any entity. That is so funky.

I need to deal with that :smile:

**Comment by FiXerCz** [comment]
**Question related to Customers page:**
By foreign key constraints it is not allowed to remove Customer with either reservation or account. Customers with reservations have their "Delete" button grayed out. Customers with account should:
- change account (remove Customer link) and then remove Customer object?
- remove account and then Customer object?
- have the "Delete" button also grayed out?

In any case I must probably add ```getAccountByCustomer(...)``` methods to DAO and Service. Yay.

---

I have also pretty much solved authentication for REST API. I will push it when I deal with the mentioned customer problem.

**Comment by Cweorth** [comment]
Well, the answer to the question depends.
**From the role of Administrator** that removes **other** customer than his own:
  * if the customer has an account, you need to delete the account that uses it; it will automatically remove the customer (and his reservations) as well,
  * else the customer can be deleted only when he has no reservations.
**BUT** the latter case should never happen in the application, as you can't create a sole customer via application (only programatically).

**From the role of User/Staff** you can't delete any customer. All you can do is delete your *account* that will also delete your customer.

**Comment by FiXerCz** [comment]
> if the customer has an account, you need to delete the account that uses it; it will automatically remove the customer (and his reservations) as well,

Alright, so if ADMIN clicks Delete button for some Customer entry (Customer has no reservations), I will automatically call deleteAccount() and that will remove both Account and Customer. Is that correct?

**Comment by Cweorth** [comment]
Well ... you CAN do that if you want, but do you WANT TO? It would leave the operations "inconsistent" of some sort: you can automatically remove account which is *before* the customer in the dependency relation, but not reservations, which are *after* the customer?

I say, leave it be! :smiley: disable buttons of those customers that can't be deleted and for the convenience put a label there saying that "All the customers without disabled buttons can be deleted from Accounts list.". There.

**Comment by FiXerCz** [comment]
:D I love that approach.

BTW can we live without CSRF protection for authentication? Currently it is active but it is pain in the ass for authentication in REST API. Without it, "authentication" in REST works fine. Assignment does not specify that we need to have it so I would let it go :)

**Comment by Cweorth** [comment]
Leave that as it is (with CSRF on), I will look into that. (But in the end, no, we don't need it that much. If there is no time left, we will turn it off and pretend we never heard of it).

When are you planning to push? I had exams yesterday and today, so I had no time to look into this, but now I would like to finish Trips without breaking something of yours...

**Comment by FiXerCz** [comment]
Right now, I have only changes in REST (ExcursionRestController) + some nonsense when I messed around with CSRF protection (I am planning to revert those changes, so you can now pull what I just pushed and then you can change anything you like).

Should I push also the REST controller change?

**Comment by Cweorth** [comment]
No, I will not be working with REST now. Later (as in few days :smiley: ) I might do something in CLI application...

**Comment by Cweorth** [comment]
Can you push REST controller changes please?

**Comment by FiXerCz** [comment]
U mean my original attempt for authentication of rest? Sure I can do that, but as I said, it needs csrf protection turned off.

It will be pushed in max 20 minutes, I am not near pc again.

**Comment by Cweorth** [comment]
### The REST API and CLI Application are finished

And it works! Or at least I think it does...
You can try it easily, make sure the server is running, then
```bash
cd SurrealTravelCLI

# now to create runnable jar file in ./target
# this will also download all dependencies into ./target/lib
mvn package

# run the command
./run [arguments]
./run -U username [arguments] # and then it will ask for password ... ;)

# which is equivalent to
java -jar target/SurrealTravelCLI-1.0-SNAPSHOT.jar [arguments]
```

**Comment by FiXerCz** [comment]
Great! I will try as soon as I boot up my pc. :smiley:
