### ISSUE TITLE
TODO list of non-essential things

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#51]
**The list of things that should be done** at some point in time but are not essential, just polishing:

 *  cooler ```/403``` would be nice,
 *  also, link to home / back from ```/403``` ?
 *  @FiXerCz , can you add similar note that is in Trips to Excursions that cannot be deleted?
     * note that it only shows up for ```STAFF``` and if there *are* excursions that cannot be deleted,
 *  under ```logout``` or generally somewhere on main page there should be links to *delete* and *edit* the account (currently there is no way for ```USER|STAFF``` to do that except directly typing ```/accounts/edit/<my_id>```)
 *  favicon! :cake: 

You are welcome to propose your own ideas.

**Comment by FiXerCz** [comment]
>  @FiXerCz , can you add similar note that is in Trips to Excursions that cannot be deleted? note that it only shows up for STAFF and if there are excursions that cannot be deleted,

Done (for customers too). You should probably change "distribution" of BR tags around "new" button and note for trips to the same way I did it for customers and excursions. Currently if the note is not shown, the "new" button is glued to the trip listing table (no space).

I am studying for an exam, but sometime during the day I can take a look at the 403 page and prepare some JS dropdown menu for *edit* and *delete* links at the logout link.

If I come up with some other stuff, I shall post it here.

**Comment by Cweorth** [comment]
Ok thanks.

Btw, you don't have to waste your time with dropdowns, simple links would be enough I think...

**Comment by FiXerCz** [comment]
Well it is a matter of couple of minutes for me :) I just don't know how the top row (navigation + auth links) look at the monitors with smaller resolutions (I am viewing it at full hd res.). Is there still space for another links placed next to each other (when ADMIN logs in, it may be quite crowded there :smile:  )? I am lazy to pull out my NTB to check it and changing resolution at desktop would mess up my desktop icon placements :D:D

**Comment by Cweorth** [comment]
Can't you place it *under* the logout link then?

**Comment by FiXerCz** [comment]
I could. If it will look weird, I'll make that menu. It won't kill me.. Many web page elements have tried and failed..

**Comment by FiXerCz** [comment]
Ok, so edit/remove account links are in place, but I kinda failed with 403 error page. It is still boring as crap. I guess I was not feeling very creative.. If you want to, you can change it (I really won't be offended :smile: ) to sth else. That Gandalf stuff maybe..

**Comment by Cweorth** [comment]
Well... I think the page is funny :D And the links are good to, well done!

Is it possible to hide or disable "delete account" link for ```root```? You can leave it be if it would be too much work; he will simply get ```403``` in the worst case. I doubt someone will try it :smiley: but just in case...

**Comment by FiXerCz** [comment]
> Is it possible to hide or disable "delete account" link for root?

All done ;)

**Comment by Cweorth** [comment]
Thank you.

Is there anything from Security (except CLI) that needs to be finished?

**Comment by FiXerCz** [comment]
AFAIK it is just that hard-coding auth to rest api. Everything else should be done already.

**Comment by Cweorth** [comment]
Hard-coding is overrated, I have something else (yet easy) in mind :smiley:

**Comment by FiXerCz** [comment]
Okey doke, surprise me :-)

**Comment by Cweorth** [comment]
Mmm, btw, on the login screen, can you move the Submit button under the password field? Everywhere else the buttons are under fields, so it would be nice to keep it consistent.

**Comment by FiXerCz** [comment]
Sure. I am currently not at home, but I will do it when I get back.

**Comment by Cweorth** [comment]
## Summary of things yet to be finished

 - REST authentication (I'm currently revising for *Grass Seory*, but I will try to finish it today),
 - you all **should** test the Web Application with different roles, do some random stuff around to see what fails or should behave differently and report it ( :arrow_right: :bug: )
 - better (and more) trips and excursions worth of the name of Surreal-Travel :smiley: (I will do tomorrow),
 - @FiXerCz , can the *content* of the main page (the bulletin etc.) be moved to separate ```*.xhtml.(en_US|cs_CZ)``` files that can be referenced from ```*.jsp``` **without** too much effort? I fear that it should not be a part of ```*.properties``` when deploying. But we will manage without it if it would be too much work...
 - and also, there is not a mention of diagrams in the final requirements, but we changed roles (originally there was only admin and user), do you think we should change the diagrams to reflect that?

**Comment by FiXerCz** [comment]
Yo, 
point 2: already tested it and I could not find any problems.
point 3: feel free to remove the bullshit I created there for testing purposes (customers, trips I added there etc.)
point 4: no problem, I'll do it sometime today. I may add couple more phony messages there and make the bulletin look a bit better
point 5: I don't know, there is no mention of keeping those diagrams up to date. Still it is better that we have added features that are not in diagrams, than have features in diagrams that are not implemented :D If we decide to alter diagrams, I cannot be of help. Since new year I have no solid internet connection at home (lawsuit between service provider and network infrastructure provider) and I am doing everything over my carrier network and that has really tight FUP, so I cannot download VP.

**Comment by Cweorth** [comment]
I see. You should file your own lawsuit against the both of providers :smiley: I hope it will resolve soon, I mean, no fast internet for a month? You poor thing...

I think I might download it somehere, or do something similar tomorrow

**Comment by Cweorth** [comment]
Isn't it funny, that one day before finish I **finally** managed to configure CLI's ```pom.xml``` so that it can create *executable* ```.jar``` file that starts up just about 1500x faster that ```mvn exec:...``` ? :smiley: (And yes, I grew tired of waiting while the maven finds all classes and shit...)

**Comment by Cweorth** [comment]
@FiXerCz , I have a working "solution" for REST API as well as using CSRF. After several hours, it seems it required only a SINGLE EXTRA FUCKING LINE.

**springsecurity.xml**: before first ```<http...>```
```xml
<http pattern="/rest/**" auto-config="true" use-expressions="true"/>
```

This will de-facto exclude CSRF and ```AuthInterceptor``` only for REST and will leave it on for the *rest* of the pages.
How cool is this? :smiley:

**Comment by FiXerCz** [comment]
Executable .jar for cli is great news. Now I can remove those stupid custom maven goals from netbeans. Though it is interesting,that we have been told it is impossible to create executable file - maybe you can add mention to readme.md, that is is in fact working - if we've got sth to gloat about, why not do it :D:D

You gotta be kidding me about that damn REST. I have tried really all sorts of stuff - I have tried to use interceptor, disect request object to obtain csrt token and then somehow set it to response -> all of that failed (spring security check sequence was fired before interceptor). And you solve it with 1 line of code??!!! :)

But seriously, great work, it is good that we can keep the csrf on! :)

**Comment by Cweorth** [comment]
I will push it in a moment... I'm just testing some extra features :smiley:

**Comment by FiXerCz** [comment]
OMG, I must share this. I am creating some made up articles for the bulletin and I needed some hobbit names - there is a freaking hobbit name generator!! Check it out, it is hillarious!!
http://www.chriswetherell.com/hobbit/index.php

**Comment by Cweorth** [comment]
That's insane.

Btw, I have an idea how to obtain new user names... ;D

**Comment by FiXerCz** [comment]
I have noticed, that logged in staff/admin can see a bit deformed table with listing of excursions (3 buttons next to each other). In Chrome it is ok, but Firefox requires probably a bit more space. Changing the width of a last table column from 200 to 210 solves the issue in Firefox.

**Comment by Cweorth** [comment]
oh god ... I don't really remember where these numbers are, can you fix it, please?

**Comment by FiXerCz** [comment]
Sure thing. I will do it in the morning.

**Comment by Cweorth** [comment]
Mmm, I tried it here on Firefox, but the buttons showed OK. Anyway, I increased the width.

**Comment by Cweorth** [comment]
What about this ```/403```?

![output](https://cloud.githubusercontent.com/assets/3329989/5889830/ab41b246-a43a-11e4-87b6-09e2124a868a.gif)

The White Wizard has **403** reasons not to let you see you this page. That rascal is probably up to something.

The problem is that I used ffmpeg to create frames from FullHD film and even when I resized it to 320x240, the size is still 3.3 M :sad:

**Comment by FiXerCz** [comment]
Yeah, that will be great :-) Maybe the 403 page should contain just that video, message and return link, i.e. it should not be based on layout tag, which would add menu, titles etc. That way the elements could be centered on the page and it would not look weird. What do u think?

**Comment by Cweorth** [comment]
Sorry, I forgot to mention that it's not a video, but GIF (but 1.8M GIF is not very far from actual video :smiley:). I will try to add it and see how it looks.

**Comment by Cweorth** [comment]
I have managed to decrease the size to 800K, which is almost perfect :smiley: I have also "generalized" your ```bulletin``` and reused it (it's a good component :smiley:) and I have created this

![screenshot from 2015-01-25 11 51 38](https://cloud.githubusercontent.com/assets/3329989/5891222/bae2ea14-a488-11e4-8e21-67422d9bff9d.png)

What do you think? Should I change something before I push it?

**Comment by dvori** [comment]
I think it's great, I like it ... I wouldn't change anything :smiley:

**Comment by Cweorth** [comment]
While I'm at it, any ideas for 404 and 500? :smiley:

**Comment by FiXerCz** [comment]
I concur with dvori, it looks great!! :smiley:

point 404: "This is not the page you are looking for" and yoda? :)
point 500: no idea yet

**Comment by Cweorth** [comment]
Ad 500: I'd use Daenerys' Sake of Astapor (lots of fire, explosions etc.)
Ad 404: I thought about it, but it's already overly used. I want to be original :smiley: But I will probably use Yoda if I can't think of anything else

**Comment by FiXerCz** [comment]
Alright, 500 error message sound good. I have edited my previous post, github does not notify about that :)

**Comment by Cweorth** [comment]
Aaa, Palantir ... that sounds great :D I just need to create GIF from the film ... :smiley:

**Comment by Cweorth** [comment]
Ok, I tried to be original :D what do you think about this 404?

![screenshot from 2015-01-25 13 04 45](https://cloud.githubusercontent.com/assets/3329989/5891386/c0f17560-a492-11e4-863b-3989d9bc5ed1.png)

The GIF is from the 2001: Space Odyssey

**Comment by FiXerCz** [comment]
Yep, I bet no one has that yet :)

**Comment by Cweorth** [comment]
and finally

![screenshot from 2015-01-25 13 59 57](https://cloud.githubusercontent.com/assets/3329989/5891510/7a2eebfa-a49a-11e4-90a2-5083cbde5844.png)

Close Encounters of the Third Kind 
(The GIF from Game of Thrones was too bad of quality :disappointed: )

**Comment by FiXerCz** [comment]
Nice. Do you realize that we should deliberatly do sth wrong during live demo of our presentation just so we could show those messages? :-D It would be shame not to.

**Comment by Cweorth** [comment]
Oooooo ... well, I don't know about any errors (I would repair them :smiley:) but when I deploy the app to my work computer, I can add the mapping to "/fail" to throw an exception and show this page (it will NOT be in the "official" source of course)

**Comment by Cweorth** [comment]
Btw, do you think we should add some *legal* information somewhere that we do not own these pictures?

**Comment by FiXerCz** [comment]
We can show 403 and 404 pages easily at the end of presentation, by changing url to access eiher restricted or non-existent content. Just as a "borec na konec" ending :-)

Yeah, I think legal information should be at the bottom of all error pages. Sth like "we do not own any rights for the image material. Content is owned by appropriate-movie-studio-title."

**Comment by Cweorth** [comment]
I added this

```xhtml
<br/>
<small>
    The Surreal-Travel does not own rights for the image material on this page.<br/>
    The content from <i>2001: A Space Odyssey</i> (film) is owned by Metro-Goldwyn-Mayer.
</small>
```
to ends of the pages, hope it will be enough.

Also, I pushed it! Now I'm going to create some nice entities :smiley:

**Comment by FiXerCz** [comment]
I have a question/improvement proposal regarding creating new ROLE_USER accounts.

*Question first:* a) If a visitor, who is not authenticated wants to create account, we can assume, that that person wants a Customer account, right (Customer included)? b) If we want to create account, that will not have customer (staff or admin), we would be probably logged in as an ADMIN or ROOT (employees do not usually create their accounts from a scratch - they receive login info and can change account details l8r). Am I correct in thinking this?

*Now proposal:* Users are generally stupid. It may be harsh, but it is true. Having in new-account form checkbox "is customer?" may lead to situations, when visitor creates account without customer (deselects checkbox) - such account is useless for him, since he cannot create reservations. My proposal is this: Lets hide checkbox from new-form for anyone who is not authenticated or less than admin. Logged in admins would see new-form as it is now.

This can be achieved easily:

Adding this just below taglib imports:
```jsp
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>

<sec:authorize access="not hasRole('ROLE_ADMIN')">
  <input type="hidden" name="customer" id="customer" value="1"/>
</sec:authorize>
```

And replacing table row with checkbox with this:
```jsp
<sec:authorize access="hasRole('ROLE_ADMIN')">
  <tr>
    <td class="left">  <f:message key="account.customer"/>:</td>
    <td><form:checkbox path="customer" id="customer"/></td>
  </tr>
</sec:authorize>
```

If you see any flaws in my assumption or just do not want to do this (it is quite last minute proposal), then disregard this. It is just an idea.

**Comment by Cweorth** [comment]
I have no objections against this. If you have a working copy, test it and push it please (we are quite running out of time :smiley: so I can't do it myself)

**Comment by FiXerCz** [comment]
Okey, doke I will also fix a return value for 403 method in AuthController to point to new template location.

**Comment by Cweorth** [comment]
use address ```/403```, this will get mapped to the right page... so that if (someone, someday) decides to move error pages, he won't have to search the whole code, but will only change the mapping in the Controller :smiley:

**Comment by FiXerCz** [comment]
Oh, lol I can even remove method with that mapping. It is probably done by Spring Security now :D

**Comment by Cweorth** [comment]
what method?

**Comment by FiXerCz** [comment]
Sorry, I did not see your message. I had mapping for 403 error page in AuthController. You have added it for a bit different mapping to ErrorController. So i removed it from AuthController, as now it makes more sense in ErrorController.

I have also noticed that Chrome + IE have different value for *locale* than Firefox, so we need to change comparisons for deciding what template to include to this:

```jsp
${pageContext.request.locale == 'cs' || pageContext.request.locale == 'cs_CZ'}
```

That works in all 3 browsers.

**Comment by Cweorth** [comment]
Dammit ... ok, I will change it when I finish examples (20 Excursions, 7 Trips, so far 7 Customer) ... enough? :D

**Comment by FiXerCz** [comment]
I think it is enough, but if you are enjoying yourself, then by all means, keep it on :D:D

**Comment by Cweorth** [comment]
Did you change some of *.jsp files?

Also, can you czech the check version of those error pages? ( :wink: )

**Comment by FiXerCz** [comment]
In my last commit I have changed *index.jsp* and *account/form.jsp*.

Sure, I can look at the translations.

:D:D You have added *Wherever the wind takes me*. I forgot to ask you to that, but obviously I did not have to.

I have also just tested authentication for REST. Works great, nice job! I wonder how many other teams will have authentication there ;)

**Comment by Cweorth** [comment]
But I have forgot to add the *discount tours to Alpha Centauri Bb* :smiley: But I have found another error (the condition when to disable Trips' delete button is inversed), so I will fix both

**Comment by FiXerCz** [comment]
I found only minor mistakes. Can I correct them directly? It would be easier.

Should I also add the conditions to error pages for checking for "cs_CZ" locale?

**Comment by Cweorth** [comment]
Well, I found more compact condition:
```jsp
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<c:when test="${fn:startsWith(pageContext.response.locale, 'cs')}"> ... </c:when>
```

which works for any ```cs_CZ``` or ```cs_CZ.utf8``` etc., but it does not matter, if you fixed it already

**Comment by FiXerCz** [comment]
Alright, I can use that. I knew there will be something to check the prefix but i was too lazy to look for that :D

I will push it along with grammar corrections.

**Comment by FiXerCz** [comment]
Ok, it is done.

**Comment by Cweorth** [comment]
Ad "iPad owners only": Did you notice the price? :smiley:

Also, it is quite strange that you can login into REST API as an USER and delete trips and excursions... :smiley:

**Comment by Cweorth** [comment]
... and the reason is that certain team leader is a moron and forgot to add ```@Secured``` annotations on Service layer.

**Comment by FiXerCz** [comment]
I did notice price. And the travel guide on that excursion should be called Bender. It relates to iPhones, but what the hell.. :smiley:

**Comment by Cweorth** [comment]
:smiley: Ok, so, what's left?

**Comment by FiXerCz** [comment]
I think we are done. All requirements are met. Maybe we can do final check, if everything works (click it through) and try clean build (repo checkout and build?). I have also seen some commented out code in JPAAccountDAOTest. Does anything else come in mind?

I will add my slides with my assesment of this subject tomorow, as tomorow I will be studying for java exam so I will do it both.

Btw I have just read requirements again and I think that deadline was an hour ago :D But hopefully it won't be as strict as previous checkpoints that had explicit date and time.

**Comment by FiXerCz** [comment]
Oh and readme should be updated about CLI auth. I think that just copying your entry from auth issue shoud do.

**Comment by Cweorth** [comment]
Yes, I noticed it too... well, we can argue that we didn't know the *precise* time of the deadline, since we got the exact time only on friday... but meeh. We have 40 points, what can go wrong? :smiley:

All right, let's make it faster, you check the Dao, Service and API (also documentation!), I will check the rest (Web, CLI). And I will update the Readme as well.

**Comment by FiXerCz** [comment]
Okay.

**Comment by Cweorth** [comment]
I have noticed a very odd thing:
  - some files use ```CRLF``` line endigs, some only ```LF```,
  - some files do not contain trailing ```EOL``` sequence,
  - there are many files with spaces after the last printable character

While these are not problems (well, the second one actually *is*, because a text file must end with EOL by definition), I have a script at work that can fix this all at once ... I think I may run it after we check the code :smiley:

**Comment by Cweorth** [comment]
One more thing: when you are done, you can recheck warnings automatically in NetBeans:
  1. select the root module (SurrealTravel),
  2. Navigate > Inspect
  3. Select "All analyzers" and run.

You can ignore all "Missing Javadoc", but for instance, in AccountDTO there is a warning about redundant if statement.

**Comment by FiXerCz** [comment]
Will do. I will commit per module to avoid one giant commit blob.

**Comment by Cweorth** [comment]
:scream:  how many changes did you do?

**Comment by FiXerCz** [comment]
Well it is mostly code formatting and comment typos changes, but in some tests I had to remove quite a lot of unused variables :)

And I have that checking under Source > Inspect :)

**Comment by Cweorth** [comment]
Oooo ... yes, sorry, it's under Source here in LinuxLand as well, I'm just too tired to think properly right now :smiley:

**Comment by Cweorth** [comment]
I've finished CLI and Web (there were not too many problems), so I will fix that warning and check API as well.

**Comment by FiXerCz** [comment]
I have just pushed DAO. Ok, I will do Service and leave API to you.

**Comment by FiXerCz** [comment]
Overriden methods for Default_Service have documentation, although they are documented in their interfaces in API. Shoud I remove docs from Service?

**Comment by Cweorth** [comment]
Mmm ... we created them copy-paste I remember :smiley: well, it's not a mistake to have documentation on ```@Override``` methods, so I will leave it up to you.

**Comment by FiXerCz** [comment]
That is odd, I have commited DefaultReservationService and AccountServiceTest and whenever I try to push I get notified there is conflict. Odd..

**Comment by Cweorth** [comment]
which file is conflicting? O_o try ```pull``` first (Git will not allow you to ```push``` if your have a staged commit, but master is ahead).

**Comment by FiXerCz** [comment]
When I try pull it also says that conflict would arise.

How can I revert my local commit (not pushed)?  Git > Remote > Show Outgoing > Revert Commit?

I dont want to fuck anything up.

**Comment by FiXerCz** [comment]
Yeah, incomming show your changes in API so it is just that master is one commit ahead. If I push it should merge correctly, no? It is in separate modules.

**Comment by Cweorth** [comment]
but which file would be in conflict? O_o doesn't it say?
Reverting a commit WILL be a problem, mmm, make backup of the Service layer somewhere, then revert it, pull, and copy your changed files back

**Comment by Cweorth** [comment]
(If you were using command-line GIT, I think it would be easier, as it usually precisely shows you where's the problem and how to fix it :smiley:

**Comment by FiXerCz** [comment]
It does not say which file. And there should not be any, you have changed API and I have changes in Service. Funny bussiness. I will try to revert my local commit, hopefully it will not revert stuff you have pushed to API.

**Comment by Cweorth** [comment]
We can still revert the revert :smiley:

**Comment by FiXerCz** [comment]
Well that commit chain is weird like a motherfucker, but I somehow got it there. Almost not worth the effort, since I did not change almost anything.

**Comment by Cweorth** [comment]
There's no conflict :smiley: I think it was the NetBeans' Git client wrongly interpreting what I said (the underlying Git will not allow you to push if there's a new commit in the master).

**Comment by FiXerCz** [comment]
Ok, so now you will run that magic script to fix wrong EOL etc and change readme and we are done, I suppose?

**Comment by Cweorth** [comment]
Almost. I randomly tried something and realized that when you remove your account, the customer remains for some reason :smiley:

**Comment by FiXerCz** [comment]
Whatever, lets keep it for "accounting" reasons :D Nice little economy feature.

**Comment by Cweorth** [comment]
I see why. The "CustomerService.deleteById" is secured for admins only

**Comment by Cweorth** [comment]
I will make it "for users only when ID's match or admins" :smiley:

**Comment by FiXerCz** [comment]
Oh, I have automatically set everything for Customers for admins only except for creating (cause of reservations). At that time I did not know we will be removing accounts and after it was decided, I must have forgotten to change it. Sry.

**Comment by FiXerCz** [comment]
But removing customer might during removal of account might scream, if there are reservations for that customer. You would need to remove probably those first.

**Comment by Cweorth** [comment]
I know, the original code even know about it :smiley: it failed in the last step, when removing the customer

**Comment by Cweorth** [comment]
Ok, fuck it, I can't delete customer that is referenced by account and I can't delete account that is referenced by customer. I would have to override some service methods, that I don't have time for. So, the customer will remain :smiley:

**Comment by FiXerCz** [comment]
I said it before, lets label it economy and accounting feature :-) Removing account  keeps customers for checking of... whatever needs to be checked. History of reservations or sth :smiley:

**Comment by Cweorth** [comment]
1. this is 100th comment! :balloon: :tada: :balloon: :tada: :balloon: :tada:
 2. out of 181 files, 167 were somehow erroneous :smiley:

You can see the list [here](http://pastebin.com/3ij5k8GF)
After ```[FIXD]```, the list of 3 chars contains what was fixed:
   - ```e``` - missing ```EOL``` at the end of file
   - ```c``` - ```CRLF``` instead of ```LF```
   - ```w``` - whitespaces at the end of line

Btw, the command was
```bash
./fixsrc.pl --all --ignore-path "./.git" --ignore-path "lib" --ignore-file "*.png" --ignore-file "*.gif" -v -v --level 3 --color=always > ~/fixsrc.log
```
I never though I'd actually use this script outside of work :smiley:
I'm just going to test it didn't do anything wrong

**Comment by Cweorth** [comment]
LOL, when I pushed it, Git thought I deleted and recreated all files that had ```CRLF``` endings :smiley: now I have:

```Showing 169 changed files  with 7,501 additions and 7,141 deletions.```

**Comment by FiXerCz** [comment]
Interesting statistics in both points :-)

Heh you have managed to confuse github. I thought only git could confuse programmers, not the other way around.

I will be online for another hour or so in case sth comes up with the project, but I think it is pretty much finished. Btw according to the statistics we are one of the only two teams, that have 40 points so far :-)

**Comment by Cweorth** [comment]
Well ... good for us so far :smiley: But the only thing that matters now is the defense. And the exam of course. Other teams are not important :smiley:

**Comment by Pa3u3u** [comment]
I changed README for SurrealTravelCLI. I think we are done, so I'm closing this issue.
