### ISSUE TITLE
Project Defense (part II)

### ISSUE THREAD

**Issue by Pa3u3u** [Cweorth/Surreal-Travel#52]
Gentlemen, the time of our presentation is very close (Wed 28 at 17.40 to be precise). We should probably start to think about it as well :D

I will sum up the requirements:
- precisely **15 minutes** (that is, **900 seconds**),
  - **7 minutes** presentation,
  - **2 minutes** live demo,
  - the rest (**6 minutes**) I have no idea, we'll probably sing a song or play cards,
- we should cover the following:
  1. **business logic** (what is it for and what does it do),
  2. **technologies used** (well that will be a short one :D 1. _Spring_ 2. _Hibernate_ ...)
  3. **team cooperation**
  4. **our feedback**

Now, I will prepare the presentation on Monday, but I will need you to send me **your** content for 3. and 4. (that is, what do you want to take the credit for and your feedback). It may be a text file, pdf, jpeg, video blog or a comment here, I don't care as long as I can read it somehow.
So far I think the outline should be like this:
- introduction (who we are, what was the assignment),
- brief summary of the project (a slide per layer + technologies used),
- some narcissistic slide (what our project can do),
- some realistic slide (what should have been done better, probably empty :smiley: ),
- team cooperation,
- feedback.

You are, as always, welcome to propose your own ideas.

**Comment by Cweorth** [comment]
Oh, I almost forgot: I think we should meet one hour (or at least a half) before the actual presentation and make one or two rehearsals, make sure we know the details of our project and so on.

**Comment by FiXerCz** [comment]
Meeting hour in advance seems reasonable.

How are you planning to create the presentation? Will you use google docs? If so, you add sharing for the presentation with other team members (we can send you our gmail accounts via university mail, I would not plaster my mail address over Internet). That way we can all see it and contribute our part.

**Comment by Cweorth** [comment]
You can create presentations on Google Docs? I never knew :smiley: I planned doing it in *LaTeX* and *beamer* package, but if Google Docs can do that easier, then I suppose that would be better

**Comment by kiclus** [comment]
I dont know what to write in 3 and 4 but I will make something

**Comment by Cweorth** [comment]
Ok, @FiXerCz and @kiclus , please send me you GMail emails to my IS MU account. @dvori , you sent me an email yesterday from GMail, so I will grant access for that, ok?

**Comment by Cweorth** [comment]
The link is [here](https://docs.google.com/presentation/d/1pdBQrRQABcHBQ7IauLKeQ-UAuAARKEukDmujBfXvp7k/edit?usp=sharing), but you will need to wait until I grant you an access.

**Comment by kiclus** [comment]
kiclus6@gmail.com

**Comment by Cweorth** [comment]
@kiclus I have deleted your comment to avoid your address being misused (spam etc.). Also, you should never publish your email address to public places "just like that". :smiley:

**Comment by Pa3u3u** [comment]
Hello, can you please test again that the following link works for you? [Surreal-Travel](http://mens.fi.muni.cz:8080/pa165)

Btw, I have noticed that these pages "work": [403](http://mens.fi.muni.cz:8080/pa165/403), [404](http://mens.fi.muni.cz:8080/pa165/404) and [500](http://mens.fi.muni.cz:8080/pa165/500), though strictly speaking, they should all return 404 ... :smiley: but bogger that.

Again, it runs on Apache Tomcat 8, PostgreSQL 9.1, but this time Debian 7 instead of Linux Mint...

**Comment by FiXerCz** [comment]
Yeah, it seems to be working fine. Tested from my "brand new" net provider with 3 Mbit down, 0,2 Mbit up. Somebody kill me!!!

**Comment by Pa3u3u** [comment]
I don't need to kill you, just try to download Windows Updates...  you will do that yourself :smiley:

**Comment by FiXerCz** [comment]
_Quick question:_ I have just opened slides for defence so that I could I add my slide and I noticed, that the presentation is in English. Was that requirement in some kind of email from lecturers?

**Comment by Pa3u3u** [comment]
_Quick answer_: It wasn't. But given that **all** project materials are in English and some of our tutors (including the one that sent us the schedule) do not speak Czech nor Slovak, I only assumed that it would be better to have slides in English.

Imagine that you came to defense with Czech slides and half of the committee would not understand it. Bummer. :smiley:

**Comment by FiXerCz** [comment]
Yeah, ok :smiley: i shall do my slide now.

**EDIT:**
As my slide is first and I do not follow any pattern on previous slides, I will differentiate myself with different sentence syntax :D

**Comment by FiXerCz** [comment]
Howdy,
did out tutor send any questions regarding our project? There was sth like that mentioned in requirements.

BTW exam questions in study materials are hillarious - some of them dont have answers in lecture slides.

**Comment by Pa3u3u** [comment]
No questions yet. I will let you know as soon as I get some.

Yes, they are :smiley: I will probably write the exam like this

``` java
for (Question q : questions) {
    try {
        solve(q);
    } catch (WTFException ex) {
        System.err.println(q.toString() + ": NOPE");
    }
}
```

**Comment by Pa3u3u** [comment]
Dammit, I have a stack full of `WTFException` ... :wink: :smile:

**Comment by FiXerCz** [comment]
:smiley: I have encountered WrongEncodingException. They won't make anything of my terrible handwriting..

**Comment by Pa3u3u** [comment]
So, you have _thrown_ the `WrongEncodingException` and they will encounter it? :smiley:

Btw, I have a title slide! :smiley:

**Comment by Pa3u3u** [comment]
Btw, should our names in presentation be written with titles?

**Comment by FiXerCz** [comment]
I dont think that is neccessary. But that is just my opinion.. Even lecture slides of pa165 staff dont have titles.

**EDIT:**

> So, you have thrown the WrongEncodingException and they will encounter it? :smiley:

Eh.. tomayto, tomahto.. :)

**Comment by Pa3u3u** [comment]
Mmm, can someone provide the complete list of technologies we used (per layer preferably)?

**Comment by FiXerCz** [comment]
Persistence:
JPA, Hibernate, Spring JDBC, jUnit

Service/API:
Dozer, Mockito, Spring Security, jUnit

Presentation:
web: Spring MVC, Spring Security
cli: Args4j, HTTPClient

Not sure, if all are relevant. Also, Spring spans through all layers with context, orm, aop etc.. So we could say the whole project is based on Spring framework + additional technologies per layer as above (Spring JDBC could be removed then)..

**Comment by Pa3u3u** [comment]
Ok, thank you. It's much slower than I though :cry:

**Comment by Pa3u3u** [comment]
Btw, CLI does not use HTTPClient, as it did not support REST Client, we use Spring's REST Client

**Comment by FiXerCz** [comment]
I see. I thought it originally was supposed to use it and I have seen it in dependencies, so I have put it to the list. My bad.

**Comment by Pa3u3u** [comment]
it is in the dependencies? Oh... :speak_no_evil: 

btw, what I have so far is here: 
https://drive.google.com/file/d/0B5WsTRRGOsSDY1ZFaXNnLVRUT1k/view?usp=sharing

I try to be as brief (and fast) as possible, so we will only need few seconds per slide.

**Comment by Pa3u3u** [comment]
OK I have NO IDEA right now that to write about service (except that which services are there), do you have any ideas? :smiley:

**Comment by FiXerCz** [comment]
Maybe:

_Overview:_
This would be very similar to project description (what we had in the beginning) - what can application do (we can have trips, trips with excursions, manage customers, bind them together in reservations etc)

_Interface:_
Dont know - digram, maybe? But who has the time for such things..

_Security:_
- natural choice for spring -> spring security
- secure logging in by credentials (username, password), crlf
- every role has access only to functionaly, it needs and no more etc

**Comment by dvori** [comment]
I agree with @FiXerCz about Overview ... we should put there what application can do and that should be enough.

Which diagram you would like to have in Interface?

**Comment by Pa3u3u** [comment]
I have uploaded a new version. Please, **read it** and report any problems.

**Slide 8** (presentation): needs to be finished (any ideas?)
**Slide 9**: CHECK IT, did I forget something?
**Slide 10**: will be removed,
**Slide 11**: needs to be finished

**Comment by Pa3u3u** [comment]
> Which diagram you would like to have in Interface?

Ain't nobody got time for diagrams :smiley: This needs to be finished ASAP. Dammit, I would have started sooner if I knew how long would it take

**Comment by dvori** [comment]
ok, no diagram ... do you recieved any questions from tutors regarding our project?

I found just one think, **Slide 8** - I think we can just have **REST and Command-Line Interface application** and the rest  "that can access it" delete. Mention about accesible is in first sentence on that slide.

**Comment by Pa3u3u** [comment]
There were no questions yet. I suspect I will receive them after I send him the presentation.

**Comment by FiXerCz** [comment]
Slide 8:
Shouldnt REST be incorporated to the Web? Like:
*Web service over HTTP, accessible via client's browser
- provides also RESTful service

Command-Line Interface application that can access REST service*

Or sth like that?

**Comment by FiXerCz** [comment]
that "list entry" in previous entry should be part of first line (Web service...). Github redid formatting.

**Comment by FiXerCz** [comment]
Otherwise very nice and clean presentation :+1: 

**EDIT:**
Please on slide 9 change Ján to Jan (czech version of name) :)

**Comment by dvori** [comment]
If I understand correctly file (final defense) we dont need to send this presentation in advance. But tutor should send questions 24 hour beforethe defense ...

**Comment by Pa3u3u** [comment]
... ... ... and you are saying it **NOW**?! ... fuck this, I'm going home :smiley: But I will write our tutor an email with my questions about the presentation.

**Comment by Pa3u3u** [comment]
Ok, I've sent an email to our tutor. I will let you know about the answer as soon as it arrives.

**Ad presentation**: I will finish it later, I'm still at work and past time I went home... :smiley:,
**Ad meeting**: As we are required to come 15 minutes before defense, we should (just in case) adjust the time to **16.30** somewhere in the computer hall.

**Comment by Pa3u3u** [comment]
While I'm still here, what about this slide?
![surreal-travel](https://cloud.githubusercontent.com/assets/3329989/5924997/b39d4644-a660-11e4-804f-e320ce95787e.png)

**Comment by FiXerCz** [comment]
Yeah! That is perfect. Good that you mentioned CLI authentication.

**Comment by dvori** [comment]
Agree with  @FiXerCz, that slide is perfect

**Comment by kiclus** [comment]
ok

**Comment by Pa3u3u** [comment]
## Response from our tutor
1. Ad language, **english is preferred**, Bruno Rossi will be there (as I thought), but if it was too big a problem, we **can** speak czech
   ... but I suppose we can't expect much success if one of the committee would not understand us
2. we can use my Mens for demo,
3. there are no questions for us, precisely:

> Občas sa stáva, že je projekt v stave, kedy vyžaduje vysvetlenie formou slidov, ale toto nie je ten prípad :-).

**Comment by FiXerCz** [comment]
Alrighty then. Giving presentation in English is not such a big obstacle.

**Comment by Pa3u3u** [comment]
Well, we will have to prepare it for ~6 minutes, 7 at most. Under even a slight stress, it could get longer and we don't want that. And we will also have to take into account our levels... ie. how much we really want to say :smiley:

**Comment by dvori** [comment]
I would keep presentation as it is, just delete the summary page and that should be for 6 minutes more than enough.

**Comment by Pa3u3u** [comment]
The summary is essential I believe, you wouldn't delete it from your thesis defense... would you? :wink: I did not mean the _text_, I meant our _verbal_ presentation, how much we would say about it (that's why the _text_ is very brief, to maintain some flexibility in amount of content you want to talk about)

**Comment by dvori** [comment]
You don't know, what I'm capable ... but true is that depend on the way you look on it. In this presentation could be end the feedbacks where you summaries the everything.

Yeah, what we say, not so much either ... I think we can finalize that tomorrow before our defense ...

**Comment by Pa3u3u** [comment]
:balloon: :tada: :balloon: :tada: :balloon: **WE DID IT** :balloon: :tada: :balloon: :tada: :balloon:

Good work, everyone! Sorry for the fail with the notebook, I really had no idea how bad the battery was. But I spanked it hard and it promised it won't happen again :monkey: 

And now, I solemnly close this last issue. (Unless you open another one).

---

"_All we have to decide is what to do with the time that is given us._”
"_Fly, you fools!_"
    -- Gandalf the Grey
